[tool.poetry]
name = "decotra"
version = "0.0.0-dev"
description = ""
authors = ["funwarioisii <g231q026@s.iwate-pu.ac.jp>"]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[build-system]
requires = ["poetry>=0.12", "boto3", "numpy"]
build-backend = "poetry.masonry.api"
