[tool.black]
line-length = 88
target-version = ["py36"]

[tool.poetry]
name = "shinyutils"
version = "2.0.0"
description = "Personal collection of common utilities"
authors = ["Jayanth Koushik <jnkoushik@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/jayanthkoushik/shinyutils"

classifiers=[
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Utilities",
]

[tool.poetry.dependencies]
python = "^3.6"
matplotlib = "^3.0.0"
seaborn = "^0.9.0"
crayons = "*"

[tool.poetry.dev-dependencies]
bumpversion = "*"
black = {version = "^18.3-alpha.0",allows-prereleases = true}
pylint = "^2.3"
pre-commit = "^1.15"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
