[tool.poetry]
name = "yotuyu"
version = "0.0.0-dev"
description = ""
authors = ["funwarioisii <mottirioisii@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.6"
optuna = "^0.17.1"
numpy = "^1.17"
scikit-learn = "^0.21.3"
pandas = "^0.25.2"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
